# Generated by Django 6.1.2 on 2026-10-06 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpeditionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='poid_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, "Le poid de l'expedition doit être supérieur à 0")]),
        ),
    ]
