# Generated by Django 6.1.1 on 2026-09-29 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
        ('ExpeditionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_jours', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('p', 'proposee'), ('a', 'acceptee'), ('r', 'refusee'), ('ret', 'retiree')], default='proposee', max_length=20)),
                ('date_proposition', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='EntrepriseApp.entreprise')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='ExpeditionApp.expedition')),
            ],
        ),
    ]
