# Generated by Django 6.1.1 on 2026-09-29 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OffreApp', '0001_initial'),
        ('vehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='vehiculeApp.vehicule'),
        ),
    ]
