# Generated by Django 6.1.2 on 2026-10-06 13:48

import EntrepriseApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, "L'adresse ne peut pas être inférieure à 20 caractères"), django.core.validators.MaxLengthValidator(400, "L'adresse ne peut pas dépasser les 400 caractères")]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[EntrepriseApp.models.validate_email]),
        ),
    ]
