# Generated by Django 6.1.2 on 2026-10-06 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='capacite_kg',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La capacité du véhicule doit être supérieure à 0')]),
        ),
    ]
